// <auto-generated />
using MongoDB.Bson;
using MongoDB.Driver;

namespace MyTelegram.Messenger.Handlers.LatestLayer.Payments;
/// <summary>
/// Create a <a href="https://corefork.telegram.org/api/gifts#gift-collections">star gift collection »</a>.
/// Possible errors
/// Code Type Description
/// 400 PEER_ID_INVALID The provided peer id is invalid.
/// <para><c>See <a href="https://corefork.telegram.org/method/payments.createStarGiftCollection"/> </c></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
internal sealed class CreateStarGiftCollectionHandler(
    IMongoDatabase mongoDatabase,
    IPeerHelper peerHelper,
    IIdGenerator idGenerator) : RpcResultObjectHandler<MyTelegram.Schema.Payments.RequestCreateStarGiftCollection, MyTelegram.Schema.IStarGiftCollection>, IObjectHandler
{
    protected override async Task<MyTelegram.Schema.IStarGiftCollection> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Payments.RequestCreateStarGiftCollection obj)
    {
        var peer = peerHelper.GetPeer(obj.Peer, input.UserId);
        var ownerUserId = peer.PeerId;

        var collectionsCollection = StarGiftCollectionHelper.GetCollectionsCollection(mongoDatabase);
        var savedGiftsCollection = StarGiftCollectionHelper.GetSavedGiftsCollection(mongoDatabase);

        var savedGiftIds = await StarGiftCollectionHelper.ResolveSavedGiftIdsAsync(
            savedGiftsCollection,
            peerHelper,
            obj.Stargift ?? [],
            ownerUserId,
            input.UserId);

        var collectionId = await idGenerator.NextIdAsync(IdType.CollectionId, ownerUserId);

        var ownerFilter = Builders<BsonDocument>.Filter.Eq("OwnerUserId", ownerUserId);
        var orderDoc = await collectionsCollection.Find(ownerFilter)
            .Sort(Builders<BsonDocument>.Sort.Descending("Order"))
            .FirstOrDefaultAsync();
        var nextOrder = orderDoc == null ? 0 : StarGiftCollectionHelper.GetInt(orderDoc, "Order") + 1;

        var title = obj.Title ?? string.Empty;
        var hash = StarGiftCollectionHelper.CalculateCollectionHash(collectionId, title, savedGiftIds);

        var collectionDoc = new BsonDocument
        {
            { "OwnerUserId", ownerUserId },
            { "CollectionId", collectionId },
            { "Title", title },
            { "GiftSavedIds", StarGiftCollectionHelper.ToBsonArray(savedGiftIds) },
            { "Order", nextOrder },
            { "Hash", hash }
        };
        await collectionsCollection.InsertOneAsync(collectionDoc);

        if (savedGiftIds.Count > 0)
        {
            var addFilter = Builders<BsonDocument>.Filter.And(
                Builders<BsonDocument>.Filter.Eq("OwnerUserId", ownerUserId),
                Builders<BsonDocument>.Filter.In("SavedId", savedGiftIds)
            );
            var addUpdate = Builders<BsonDocument>.Update.AddToSet("CollectionId", collectionId);
            await savedGiftsCollection.UpdateManyAsync(addFilter, addUpdate);
        }

        return await StarGiftCollectionHelper.BuildCollectionAsync(mongoDatabase, collectionDoc);
    }
}
