// <auto-generated />
using MongoDB.Bson;
using MongoDB.Driver;

namespace MyTelegram.Messenger.Handlers.LatestLayer.Payments;
/// <summary>
/// Delete a <a href="https://corefork.telegram.org/api/gifts#gift-collections">star gift collection »</a>.
/// Possible errors
/// Code Type Description
/// 400 PEER_ID_INVALID The provided peer id is invalid.
/// <para><c>See <a href="https://corefork.telegram.org/method/payments.deleteStarGiftCollection"/> </c></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
internal sealed class DeleteStarGiftCollectionHandler(
    IMongoDatabase mongoDatabase,
    IPeerHelper peerHelper) : RpcResultObjectHandler<MyTelegram.Schema.Payments.RequestDeleteStarGiftCollection, IBool>, IObjectHandler
{
    protected override async Task<IBool> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Payments.RequestDeleteStarGiftCollection obj)
    {
        var peer = peerHelper.GetPeer(obj.Peer, input.UserId);
        var ownerUserId = peer.PeerId;

        var collectionsCollection = StarGiftCollectionHelper.GetCollectionsCollection(mongoDatabase);
        var savedGiftsCollection = StarGiftCollectionHelper.GetSavedGiftsCollection(mongoDatabase);

        var collectionFilter = Builders<BsonDocument>.Filter.And(
            Builders<BsonDocument>.Filter.Eq("OwnerUserId", ownerUserId),
            Builders<BsonDocument>.Filter.Eq("CollectionId", obj.CollectionId)
        );
        var collectionDoc = await collectionsCollection.Find(collectionFilter).FirstOrDefaultAsync();
        if (collectionDoc == null)
        {
            return new TBoolTrue();
        }

        var removeGiftFilter = Builders<BsonDocument>.Filter.And(
            Builders<BsonDocument>.Filter.Eq("OwnerUserId", ownerUserId),
            Builders<BsonDocument>.Filter.AnyEq("CollectionId", obj.CollectionId)
        );
        var removeGiftUpdate = Builders<BsonDocument>.Update.Pull("CollectionId", obj.CollectionId);
        await savedGiftsCollection.UpdateManyAsync(removeGiftFilter, removeGiftUpdate);

        await collectionsCollection.DeleteOneAsync(collectionFilter);

        return new TBoolTrue();
    }
}
