// <auto-generated />
using MongoDB.Bson;
using MongoDB.Driver;
using MyTelegram.Schema.Payments;

namespace MyTelegram.Messenger.Handlers.LatestLayer.Payments;
/// <summary>
/// Fetches all <a href="https://corefork.telegram.org/api/gifts#gift-collections">star gift collections »</a> of a peer.
/// Possible errors
/// Code Type Description
/// 400 PEER_ID_INVALID The provided peer id is invalid.
/// <para><c>See <a href="https://corefork.telegram.org/method/payments.getStarGiftCollections"/> </c></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
internal sealed class GetStarGiftCollectionsHandler(
    IMongoDatabase mongoDatabase,
    IPeerHelper peerHelper) : RpcResultObjectHandler<MyTelegram.Schema.Payments.RequestGetStarGiftCollections, MyTelegram.Schema.Payments.IStarGiftCollections>, IObjectHandler
{
    protected override async Task<MyTelegram.Schema.Payments.IStarGiftCollections> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Payments.RequestGetStarGiftCollections obj)
    {
        var peer = peerHelper.GetPeer(obj.Peer, input.UserId);
        var ownerUserId = peer.PeerId;

        var collectionsCollection = StarGiftCollectionHelper.GetCollectionsCollection(mongoDatabase);
        var filter = Builders<BsonDocument>.Filter.Eq("OwnerUserId", ownerUserId);
        var sort = Builders<BsonDocument>.Sort.Ascending("Order").Ascending("CollectionId");
        var collectionDocs = await collectionsCollection.Find(filter).Sort(sort).ToListAsync();

        var collections = new TVector<IStarGiftCollection>();
        foreach (var collectionDoc in collectionDocs)
        {
            collections.Add(await StarGiftCollectionHelper.BuildCollectionAsync(mongoDatabase, collectionDoc));
        }

        var hash = StarGiftCollectionHelper.CalculateCollectionsHash(collections);
        if (obj.Hash != 0 && obj.Hash == hash)
        {
            return new TStarGiftCollectionsNotModified();
        }

        return new TStarGiftCollections { Collections = collections };
    }
}
