// <auto-generated />
using MongoDB.Bson;
using MongoDB.Driver;

namespace MyTelegram.Messenger.Handlers.LatestLayer.Payments;
/// <summary>
/// Reorder the <a href="https://corefork.telegram.org/api/gifts#gift-collections">star gift collections »</a> on an owned peer's profile.
/// Possible errors
/// Code Type Description
/// 400 PEER_ID_INVALID The provided peer id is invalid.
/// <para><c>See <a href="https://corefork.telegram.org/method/payments.reorderStarGiftCollections"/> </c></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
internal sealed class ReorderStarGiftCollectionsHandler(
    IMongoDatabase mongoDatabase,
    IPeerHelper peerHelper) : RpcResultObjectHandler<MyTelegram.Schema.Payments.RequestReorderStarGiftCollections, IBool>, IObjectHandler
{
    protected override async Task<IBool> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Payments.RequestReorderStarGiftCollections obj)
    {
        var peer = peerHelper.GetPeer(obj.Peer, input.UserId);
        var ownerUserId = peer.PeerId;

        var collectionsCollection = StarGiftCollectionHelper.GetCollectionsCollection(mongoDatabase);
        var ownerFilter = Builders<BsonDocument>.Filter.Eq("OwnerUserId", ownerUserId);
        var existingCollectionDocs = await collectionsCollection.Find(ownerFilter)
            .Sort(Builders<BsonDocument>.Sort.Ascending("Order").Ascending("CollectionId"))
            .ToListAsync();

        if (existingCollectionDocs.Count == 0)
        {
            return new TBoolTrue();
        }

        var requestedOrder = (obj.Order ?? []).Distinct().ToList();
        var existingIds = existingCollectionDocs.Select(x => StarGiftCollectionHelper.GetInt(x, "CollectionId")).ToHashSet();
        var normalizedOrder = requestedOrder.Where(existingIds.Contains).ToList();

        foreach (var existingId in existingCollectionDocs.Select(x => StarGiftCollectionHelper.GetInt(x, "CollectionId")))
        {
            if (!normalizedOrder.Contains(existingId))
            {
                normalizedOrder.Add(existingId);
            }
        }

        for (var index = 0; index < normalizedOrder.Count; index++)
        {
            var id = normalizedOrder[index];
            var filter = Builders<BsonDocument>.Filter.And(
                Builders<BsonDocument>.Filter.Eq("OwnerUserId", ownerUserId),
                Builders<BsonDocument>.Filter.Eq("CollectionId", id)
            );
            var update = Builders<BsonDocument>.Update.Set("Order", index);
            await collectionsCollection.UpdateOneAsync(filter, update);
        }

        return new TBoolTrue();
    }
}
