// <auto-generated />
using MongoDB.Bson;
using MongoDB.Driver;

namespace MyTelegram.Messenger.Handlers.LatestLayer.Payments;
/// <summary>
/// Add or remove gifts from a <a href="https://corefork.telegram.org/api/gifts#gift-collections">star gift collection »</a>, or rename the collection.
/// Possible errors
/// Code Type Description
/// 400 PEER_ID_INVALID The provided peer id is invalid.
/// <para><c>See <a href="https://corefork.telegram.org/method/payments.updateStarGiftCollection"/> </c></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
internal sealed class UpdateStarGiftCollectionHandler(
    IMongoDatabase mongoDatabase,
    IPeerHelper peerHelper) : RpcResultObjectHandler<MyTelegram.Schema.Payments.RequestUpdateStarGiftCollection, MyTelegram.Schema.IStarGiftCollection>, IObjectHandler
{
    protected override async Task<MyTelegram.Schema.IStarGiftCollection> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Payments.RequestUpdateStarGiftCollection obj)
    {
        var peer = peerHelper.GetPeer(obj.Peer, input.UserId);
        var ownerUserId = peer.PeerId;

        var collectionsCollection = StarGiftCollectionHelper.GetCollectionsCollection(mongoDatabase);
        var savedGiftsCollection = StarGiftCollectionHelper.GetSavedGiftsCollection(mongoDatabase);

        var collectionFilter = Builders<BsonDocument>.Filter.And(
            Builders<BsonDocument>.Filter.Eq("OwnerUserId", ownerUserId),
            Builders<BsonDocument>.Filter.Eq("CollectionId", obj.CollectionId)
        );
        var collectionDoc = await collectionsCollection.Find(collectionFilter).FirstOrDefaultAsync();
        if (collectionDoc == null)
        {
            RpcErrors.RpcErrors400.StargiftInvalid.ThrowRpcError();
        }

        var title = obj.Title ?? (StarGiftCollectionHelper.GetNullableString(collectionDoc!, "Title") ?? string.Empty);
        var currentSavedIds = StarGiftCollectionHelper.GetGiftSavedIds(collectionDoc!);
        var savedIds = currentSavedIds.ToList();
        var savedIdSet = new HashSet<long>(savedIds);

        var removedSavedIds = new HashSet<long>();
        var addedSavedIds = new HashSet<long>();

        if (obj.DeleteStargift?.Count > 0)
        {
            var idsToDelete = await StarGiftCollectionHelper.ResolveSavedGiftIdsAsync(
                savedGiftsCollection,
                peerHelper,
                obj.DeleteStargift,
                ownerUserId,
                input.UserId);

            if (idsToDelete.Count > 0)
            {
                foreach (var id in idsToDelete)
                {
                    if (savedIdSet.Remove(id))
                    {
                        removedSavedIds.Add(id);
                    }
                }

                savedIds = savedIds.Where(x => !removedSavedIds.Contains(x)).ToList();
            }
        }

        if (obj.AddStargift?.Count > 0)
        {
            var idsToAdd = await StarGiftCollectionHelper.ResolveSavedGiftIdsAsync(
                savedGiftsCollection,
                peerHelper,
                obj.AddStargift,
                ownerUserId,
                input.UserId);

            foreach (var id in idsToAdd)
            {
                if (!savedIdSet.Add(id))
                {
                    continue;
                }

                addedSavedIds.Add(id);
                savedIds.Add(id);
            }
        }

        if (obj.Order?.Count > 0)
        {
            var orderedIds = await StarGiftCollectionHelper.ResolveSavedGiftIdsAsync(
                savedGiftsCollection,
                peerHelper,
                obj.Order,
                ownerUserId,
                input.UserId);

            var orderedExisting = orderedIds.Where(savedIdSet.Contains).Distinct().ToList();
            if (orderedExisting.Count > 0)
            {
                var tail = savedIds.Where(x => !orderedExisting.Contains(x));
                savedIds = orderedExisting.Concat(tail).ToList();
            }
        }

        if (removedSavedIds.Count > 0)
        {
            var removeFilter = Builders<BsonDocument>.Filter.And(
                Builders<BsonDocument>.Filter.Eq("OwnerUserId", ownerUserId),
                Builders<BsonDocument>.Filter.In("SavedId", removedSavedIds)
            );
            var removeUpdate = Builders<BsonDocument>.Update.Pull("CollectionId", obj.CollectionId);
            await savedGiftsCollection.UpdateManyAsync(removeFilter, removeUpdate);
        }

        if (addedSavedIds.Count > 0)
        {
            var addFilter = Builders<BsonDocument>.Filter.And(
                Builders<BsonDocument>.Filter.Eq("OwnerUserId", ownerUserId),
                Builders<BsonDocument>.Filter.In("SavedId", addedSavedIds)
            );
            var addUpdate = Builders<BsonDocument>.Update.AddToSet("CollectionId", obj.CollectionId);
            await savedGiftsCollection.UpdateManyAsync(addFilter, addUpdate);
        }

        var hash = StarGiftCollectionHelper.CalculateCollectionHash(obj.CollectionId, title, savedIds);
        var update = Builders<BsonDocument>.Update
            .Set("Title", title)
            .Set("GiftSavedIds", StarGiftCollectionHelper.ToBsonArray(savedIds))
            .Set("Hash", hash);
        await collectionsCollection.UpdateOneAsync(collectionFilter, update);

        collectionDoc["Title"] = title;
        collectionDoc["GiftSavedIds"] = StarGiftCollectionHelper.ToBsonArray(savedIds);
        collectionDoc["Hash"] = hash;

        return await StarGiftCollectionHelper.BuildCollectionAsync(mongoDatabase, collectionDoc);
    }
}
